[book]
title = "ant-quic Documentation"
authors = ["ant-quic contributors"]
language = "en"
src = "src"

[build]
build-dir = "book"

[output.html]
git-repository-url = "https://github.com/dirvine/ant-quic"
git-repository-icon = "fa-github"