[package]
name = "bench"
version = "0.1.0"
authors = ["Benjamin Saunders <ben.e.saunders@gmail.com>"]
edition = "2018"
license = "MIT/Apache-2.0"
publish = false

[dependencies]
anyhow = "1.0.22"
futures = "0.3.1"
quinn = { path = "../quinn" }
rcgen = "0.8"
rustls = "0.17"
tokio = { version = "0.2.13", features = ["rt-core"] }
tracing = "0.1.10"
tracing-subscriber = { version = "0.2.3", default-features = false, features = ["env-filter", "fmt", "ansi", "chrono"]}

[[bin]]
name = "bulk"
path = "src/bulk.rs"
