[package]
name = "interop"
version = "0.1.0"
authors = ["Benjamin Saunders <ben.e.saunders@gmail.com>", "Jean-Christophe BEGUE <begue.jc@gmail.com>"]
edition = "2018"
default-run = "main"

[dependencies]
anyhow = "1.0.22"
bytes = "0.5.2"
futures = "0.3.1"
http = "0.2"
quinn = { path = "../quinn" }
quinn-h3 = { path = "../quinn-h3" }
quinn-proto = { path = "../quinn-proto" }
rustls = { version = "0.16", features = ["dangerous_configuration"] }
structopt = "0.3.0"
tokio = { version = "0.2.2", features = ["rt-core", "io-util"] }
tracing = "0.1.10"
tracing-subscriber = "0.1.5"
webpki = "0.21"

[[bin]]
name = "main"
path = "src/main.rs"

# [[bin]]
# name = "qif"
# path = "src/qif.rs"
